src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: 'users')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, nullable: true)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    // not persisted
    private ?string $plainPassword = null;

    #[ORM\Column]
    private bool $isVerified = false;

    #[ORM\Column(length: 48)]
    private ?string $code = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cel = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isArtist = null;

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCel(): ?string
    {
        return $this->cel;
    }

    public function setCel(?string $cel): static
    {
        $this->cel = $cel;

        return $this;
    }

    public function isArtist(): ?bool
    {
        return $this->isArtist;
    }

    public function setIsArtist(?bool $isArtist): static
    {
        $this->isArtist = $isArtist;

        return $this;
    }
}

templates/components/Obras.html.twig
{#  this is used by <twig:Obras> #}


<h3>{{ obras|length }} Obras</h3>
<table class="table">
    <thead>
    <tr>
        <th>QR</th>
        <th>Media</th>
        <th>Info</th>
    </tr>
    </thead>
    <tbody>
    {% for obra in obras %}
        <tr>
            <td>
                {# this should not be done in TWIG!  quick hack for debugging #}
                {% set mobile_base = app.request.get('base', mobile_base)  %}

{#                https://pgsc.wip/artists/13?debug=1&base=fw.survos.com#}
                {% if not (mobile_base matches '/http/') %}
                    {% set mobile_base = 'https://' ~ mobile_base %}
                {% endif %}
                {% set url = mobile_base ~ path('mobile_obra', obra.rp) %}
                {% set url = mobile_base ~ '?id=%d#tab-obras'|format(obra.id) %}

                <a href="{{ url }}" target="_blank">
                    <img src="{{ qr_code_url(url) }}" />
                    <div class="print-group">
                    </div>
                    {% if app.request.get('debug', false) %}
                    {{ url }}
                    {% endif %}
                </a>
            </td>
            <td>
                {% for image in obra.images %}
                    {{ image.originalUrl }}
{#                    @todo: image {{ image.name }}#}
{#                    {{ dump(image) }}#}
{#                    <img src="{{ image }}"/>#}

                {% endfor %}
            </td>
            <td>

                <h3>{{ obra.title }}</h3>
                {% if obra.description %}
                    <p>
                        {{ obra.description|raw }}
                    </p>
                {% endif %}
                {% if showArtist %}
                    <i>por {{ obra.artist }}</i>
                {% endif %}
                {% if showLocation %}
                    {% if obra.location %}
                        <code>@{{ obra.location }}</code>
                    {% else %}
                        {{ 'no-location'|trans }}
                    {% endif %}
                {% endif %}
                <twig:ux:icon name="tabler:currency-dollar" />{{ obra.price|number_format }}
            </td>

        </tr>
    {% endfor %}

    </tbody>
</table>
</ol>